//
// ChannelReferencesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelReferencesRequest: Codable {

    /** The unique ChannelEngine product ID. */
    public var _id: Int?
    /** The unique product reference used by the Channel */
    public var channelProductNo: String?


    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case channelProductNo = "ChannelProductNo"
    }


}

