//
// ChannelCancellationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelCancellationResponse: Codable {

    public enum ReasonCode: String, Codable { 
        case notInStock = "NOT_IN_STOCK"
        case damaged = "DAMAGED"
        case incomplete = "INCOMPLETE"
        case clientCancelled = "CLIENT_CANCELLED"
        case invalidAddress = "INVALID_ADDRESS"
        case other = "OTHER"
    }
    /** The unique order reference used by the Channel */
    public var channelOrderNo: String
    public var lines: [ChannelCancellationLineResponse]
    /** The date at which the cancellation was created in ChannelEngine */
    public var createdAt: Date?
    /** The date at which the cancellation was last modified in ChannelEngine */
    public var updatedAt: Date?
    /** Reason for cancellation (text) */
    public var reason: String?
    /** Reason code for cancellation */
    public var reasonCode: ReasonCode?


    public enum CodingKeys: String, CodingKey { 
        case channelOrderNo = "ChannelOrderNo"
        case lines = "Lines"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case reason = "Reason"
        case reasonCode = "ReasonCode"
    }


}

