//
// ChannelCancellationLineResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelCancellationLineResponse: Codable {

    /** The unique product reference used by the Channel */
    public var channelProductNo: String
    /** Quantity of the product to cancel */
    public var quantity: Int


    public enum CodingKeys: String, CodingKey { 
        case channelProductNo = "ChannelProductNo"
        case quantity = "Quantity"
    }


}

