//
// ChannelReturnLineResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelReturnLineResponse: Codable {

    /** The unique product reference used by the Channel */
    public var channelProductNo: String
    /** Number of items of the product in this return */
    public var quantity: Int


    public enum CodingKeys: String, CodingKey { 
        case channelProductNo = "ChannelProductNo"
        case quantity = "Quantity"
    }


}

