//
// ChannelOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelOrderRequest: Codable {

    /** The unique order reference used by the Channel */
    public var channelOrderNo: String
    /** The order lines */
    public var lines: [ChannelOrderLineRequest]
    /** The customer&#39;s telephone number */
    public var phone: String?
    /** The customer&#39;s email */
    public var email: String
    /** Optional. A company&#39;s chamber of commerce number */
    public var companyRegistrationNo: String?
    /** Optional. A company&#39;s VAT number */
    public var vatNo: String?
    /** The payment method used on the order */
    public var paymentMethod: String?
    /** The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsInclVat: Double
    /** The currency code for the amounts of the order */
    public var currencyCode: String
    /** The date the order was done */
    public var orderDate: Date
    /** The unique customer reference used by the channel */
    public var channelCustomerNo: String?
    /** The billing or invoice address */
    public var billingAddress: Address
    /** The shipping address */
    public var shippingAddress: Address
    /** Extra data on the order */
    public var extraData: [String:String]?


    public enum CodingKeys: String, CodingKey { 
        case channelOrderNo = "ChannelOrderNo"
        case lines = "Lines"
        case phone = "Phone"
        case email = "Email"
        case companyRegistrationNo = "CompanyRegistrationNo"
        case vatNo = "VatNo"
        case paymentMethod = "PaymentMethod"
        case shippingCostsInclVat = "ShippingCostsInclVat"
        case currencyCode = "CurrencyCode"
        case orderDate = "OrderDate"
        case channelCustomerNo = "ChannelCustomerNo"
        case billingAddress = "BillingAddress"
        case shippingAddress = "ShippingAddress"
        case extraData = "ExtraData"
    }


}

