//
// ChannelProductReferencesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelProductReferencesRequest: Codable {

    /** The unique ChannelEngine product ID. */
    public var _id: Int?
    /** The unique product reference used by the Channel */
    public var channelProductNo: String?

    public init(_id: Int?, channelProductNo: String?) {
        self._id = _id
        self.channelProductNo = channelProductNo
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case channelProductNo = "ChannelProductNo"
    }


}

