name: ChannelEngineChannelApiClient
targets:
  ChannelEngineChannelApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [ChannelEngineChannelApiClient]
    info:
      path: ./Info.plist
      version: 2.13.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
