name: ChannelEngineChannelApiClient
targets:
  ChannelEngineChannelApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [ChannelEngineChannelApiClient]
    info:
      path: ./Info.plist
      version: 2.9.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
