//
// CancellationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CancellationAPI {

    /**
     Get Cancellations.
     
     - parameter createdSince: (query) The date from which you will get all created cancellations (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func cancellationIndex(createdSince: Date? = nil, apiResponseQueue: DispatchQueue = ChannelEngineChannelApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: CollectionOfChannelCancellationResponse?, _ error: Error?) -> Void)) {
        cancellationIndexWithRequestBuilder(createdSince: createdSince).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Cancellations.
     - GET /v2/cancellations
     - Gets all cancellations created since the supplied date.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter createdSince: (query) The date from which you will get all created cancellations (optional)
     - returns: RequestBuilder<CollectionOfChannelCancellationResponse> 
     */
    open class func cancellationIndexWithRequestBuilder(createdSince: Date? = nil) -> RequestBuilder<CollectionOfChannelCancellationResponse> {
        let localVariablePath = "/v2/cancellations"
        let localVariableURLString = ChannelEngineChannelApiClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "createdSince": createdSince?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionOfChannelCancellationResponse>.Type = ChannelEngineChannelApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
