//
// ChannelReturnRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelReturnRequest: Codable, Hashable {

    /** The unique order reference used by the Channel. */
    public var channelOrderNo: String?
    /** The unique order reference used by the Merchant (sku). */
    public var merchantOrderNo: String?
    /** The unique return reference used by the Channel. */
    public var channelReference: String
    /** Optional. Is the MON used as key for the order (default value is false). */
    public var keyIsMerchantOrderNo: Bool?
    /** Optional. Is the MPN used as key for the product (default value is false). */
    public var keyIsMerchantProductNo: Bool?
    public var lines: [ChannelReturnLineRequest]
    public var status: ChannelReturnStatus?
    /** The unique return reference used by ChannelEngine. */
    public var id: Int?
    public var reason: ReturnReason?
    /** Optional. Comment of customer on the (reason of) the return. */
    public var customerComment: String?
    /** Optional. Comment of merchant on the return. */
    public var merchantComment: String?
    /** Refund amount incl. VAT. */
    public var refundInclVat: Double?
    /** Refund amount excl. VAT. */
    public var refundExclVat: Double?
    /** The date at which the return was originally created in the source system (if available). */
    public var returnDate: Date?
    /** Extra data on the return. Each item must have an unqiue key */
    public var extraData: [String: String]?

    public init(channelOrderNo: String? = nil, merchantOrderNo: String? = nil, channelReference: String, keyIsMerchantOrderNo: Bool? = nil, keyIsMerchantProductNo: Bool? = nil, lines: [ChannelReturnLineRequest], status: ChannelReturnStatus? = nil, id: Int? = nil, reason: ReturnReason? = nil, customerComment: String? = nil, merchantComment: String? = nil, refundInclVat: Double? = nil, refundExclVat: Double? = nil, returnDate: Date? = nil, extraData: [String: String]? = nil) {
        self.channelOrderNo = channelOrderNo
        self.merchantOrderNo = merchantOrderNo
        self.channelReference = channelReference
        self.keyIsMerchantOrderNo = keyIsMerchantOrderNo
        self.keyIsMerchantProductNo = keyIsMerchantProductNo
        self.lines = lines
        self.status = status
        self.id = id
        self.reason = reason
        self.customerComment = customerComment
        self.merchantComment = merchantComment
        self.refundInclVat = refundInclVat
        self.refundExclVat = refundExclVat
        self.returnDate = returnDate
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelOrderNo = "ChannelOrderNo"
        case merchantOrderNo = "MerchantOrderNo"
        case channelReference = "ChannelReference"
        case keyIsMerchantOrderNo = "KeyIsMerchantOrderNo"
        case keyIsMerchantProductNo = "KeyIsMerchantProductNo"
        case lines = "Lines"
        case status = "Status"
        case id = "Id"
        case reason = "Reason"
        case customerComment = "CustomerComment"
        case merchantComment = "MerchantComment"
        case refundInclVat = "RefundInclVat"
        case refundExclVat = "RefundExclVat"
        case returnDate = "ReturnDate"
        case extraData = "ExtraData"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channelOrderNo, forKey: .channelOrderNo)
        try container.encodeIfPresent(merchantOrderNo, forKey: .merchantOrderNo)
        try container.encode(channelReference, forKey: .channelReference)
        try container.encodeIfPresent(keyIsMerchantOrderNo, forKey: .keyIsMerchantOrderNo)
        try container.encodeIfPresent(keyIsMerchantProductNo, forKey: .keyIsMerchantProductNo)
        try container.encode(lines, forKey: .lines)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(customerComment, forKey: .customerComment)
        try container.encodeIfPresent(merchantComment, forKey: .merchantComment)
        try container.encodeIfPresent(refundInclVat, forKey: .refundInclVat)
        try container.encodeIfPresent(refundExclVat, forKey: .refundExclVat)
        try container.encodeIfPresent(returnDate, forKey: .returnDate)
        try container.encodeIfPresent(extraData, forKey: .extraData)
    }
}

