//
// ChannelReturnStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ChannelReturnStatus: String, Codable, CaseIterable {
    case inProgress = "IN_PROGRESS"
    case received = "RECEIVED"
}
