//
// ChannelCancellationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ChannelCancellationResponse: Codable, Hashable {

    /** The unique order reference used by the Channel. */
    public var channelOrderNo: String
    public var lines: [ChannelCancellationLineResponse]
    /** The date at which the cancellation was created in ChannelEngine. */
    public var createdAt: Date?
    /** The date at which the cancellation was last modified in ChannelEngine. */
    public var updatedAt: Date?
    /** Reason for cancellation (text). */
    public var reason: String?
    public var reasonCode: MancoReason?

    public init(channelOrderNo: String, lines: [ChannelCancellationLineResponse], createdAt: Date? = nil, updatedAt: Date? = nil, reason: String? = nil, reasonCode: MancoReason? = nil) {
        self.channelOrderNo = channelOrderNo
        self.lines = lines
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.reason = reason
        self.reasonCode = reasonCode
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelOrderNo = "ChannelOrderNo"
        case lines = "Lines"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case reason = "Reason"
        case reasonCode = "ReasonCode"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelOrderNo, forKey: .channelOrderNo)
        try container.encode(lines, forKey: .lines)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(reasonCode, forKey: .reasonCode)
    }



}
