//
// ChannelProductChangesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelProductChangesResponse: Codable { 


    public var toBeCreated: [ChannelProductResponse]?
    public var toBeUpdated: [ChannelProductResponse]?
    public var toBeRemoved: [String]?

    public init(toBeCreated: [ChannelProductResponse]? = nil, toBeUpdated: [ChannelProductResponse]? = nil, toBeRemoved: [String]? = nil) {
        self.toBeCreated = toBeCreated
        self.toBeUpdated = toBeUpdated
        self.toBeRemoved = toBeRemoved
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case toBeCreated = "ToBeCreated"
        case toBeUpdated = "ToBeUpdated"
        case toBeRemoved = "ToBeRemoved"
    }

}
