//
// ChannelProcessedChangesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ChannelProcessedChangesRequest: Codable, Hashable {

    /** A collection of pairs of merchant and channel references  of the products which are successfully created. The channel references  are saved such that in subsequent calls these can be used instead of the  merchant references. */
    public var created: [ChannelProductReferencesRequest]?
    /** The channel references of the products which are successfully updated. */
    public var updated: [String]?
    /** The channel references of the products which are successfully removed. */
    public var removed: [String]?

    public init(created: [ChannelProductReferencesRequest]? = nil, updated: [String]? = nil, removed: [String]? = nil) {
        self.created = created
        self.updated = updated
        self.removed = removed
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created = "Created"
        case updated = "Updated"
        case removed = "Removed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(removed, forKey: .removed)
    }



}
