//
// ChannelReturnRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelReturnRequest: Codable { 


    /** The unique order reference used by the Channel. */
    public var channelOrderNo: String?
    /** The unique order reference used by the Merchant (sku). */
    public var merchantOrderNo: String?
    /** The unique return reference used by the Channel. */
    public var channelReference: String
    /** Optional. Is the MON used as key for the order (default value is false). */
    public var keyIsMerchantOrderNo: Bool?
    /** Optional. Is the MPN used as key for the product (default value is false). */
    public var keyIsMerchantProductNo: Bool?
    public var lines: [ChannelReturnLineRequest]
    /** The unique return reference used by ChannelEngine. */
    public var id: Int?
    public var reason: ReturnReason?
    /** Optional. Comment of customer on the (reason of) the return. */
    public var customerComment: String?
    /** Optional. Comment of merchant on the return. */
    public var merchantComment: String?
    /** Refund amount incl. VAT. */
    public var refundInclVat: Double?
    /** Refund amount excl. VAT. */
    public var refundExclVat: Double?

    public init(channelOrderNo: String? = nil, merchantOrderNo: String? = nil, channelReference: String, keyIsMerchantOrderNo: Bool? = nil, keyIsMerchantProductNo: Bool? = nil, lines: [ChannelReturnLineRequest], id: Int? = nil, reason: ReturnReason? = nil, customerComment: String? = nil, merchantComment: String? = nil, refundInclVat: Double? = nil, refundExclVat: Double? = nil) {
        self.channelOrderNo = channelOrderNo
        self.merchantOrderNo = merchantOrderNo
        self.channelReference = channelReference
        self.keyIsMerchantOrderNo = keyIsMerchantOrderNo
        self.keyIsMerchantProductNo = keyIsMerchantProductNo
        self.lines = lines
        self.id = id
        self.reason = reason
        self.customerComment = customerComment
        self.merchantComment = merchantComment
        self.refundInclVat = refundInclVat
        self.refundExclVat = refundExclVat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case channelOrderNo = "ChannelOrderNo"
        case merchantOrderNo = "MerchantOrderNo"
        case channelReference = "ChannelReference"
        case keyIsMerchantOrderNo = "KeyIsMerchantOrderNo"
        case keyIsMerchantProductNo = "KeyIsMerchantProductNo"
        case lines = "Lines"
        case id = "Id"
        case reason = "Reason"
        case customerComment = "CustomerComment"
        case merchantComment = "MerchantComment"
        case refundInclVat = "RefundInclVat"
        case refundExclVat = "RefundExclVat"
    }

}
