//
// ChannelOfferResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ChannelOfferResponse: Codable, Hashable {

    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?
    public var merchantProductNo: String?
    public var price: Double?
    public var stock: Int?

    public init(channelProductNo: String? = nil, merchantProductNo: String? = nil, price: Double? = nil, stock: Int? = nil) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.price = price
        self.stock = stock
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case price = "Price"
        case stock = "Stock"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channelProductNo, forKey: .channelProductNo)
        try container.encodeIfPresent(merchantProductNo, forKey: .merchantProductNo)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(stock, forKey: .stock)
    }



}
