//
// ChannelReturnLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelReturnLineRequest: Codable { 


    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?
    /** The unique product reference used by the Merchant. */
    public var merchantProductNo: String?
    /** Number of items of the product in this return. */
    public var quantity: Int

    public init(channelProductNo: String? = nil, merchantProductNo: String? = nil, quantity: Int) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
    }

}
