//
// ChannelShipmentLineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ChannelShipmentLineResponse: Codable, Hashable {

    /** The unique product reference used by the Channel. */
    public var channelProductNo: String
    /** The unique product reference used by the Merchant. */
    public var merchantProductNo: String?
    public var orderLine: ChannelOrderLineResponse?
    public var shipmentStatus: ShipmentLineStatus?
    /** Number of items of the product in the shipment. */
    public var quantity: Int

    public init(channelProductNo: String, merchantProductNo: String? = nil, orderLine: ChannelOrderLineResponse? = nil, shipmentStatus: ShipmentLineStatus? = nil, quantity: Int) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.orderLine = orderLine
        self.shipmentStatus = shipmentStatus
        self.quantity = quantity
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case orderLine = "OrderLine"
        case shipmentStatus = "ShipmentStatus"
        case quantity = "Quantity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelProductNo, forKey: .channelProductNo)
        try container.encodeIfPresent(merchantProductNo, forKey: .merchantProductNo)
        try container.encodeIfPresent(orderLine, forKey: .orderLine)
        try container.encodeIfPresent(shipmentStatus, forKey: .shipmentStatus)
        try container.encode(quantity, forKey: .quantity)
    }



}
