//
// ChannelOfferResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelOfferResponse: Codable { 


    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?
    public var merchantProductNo: String?
    public var price: Double?
    public var stock: Int?

    public init(channelProductNo: String? = nil, merchantProductNo: String? = nil, price: Double? = nil, stock: Int? = nil) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.price = price
        self.stock = stock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case price = "Price"
        case stock = "Stock"
    }

}
