//
// ChannelShipmentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelShipmentResponse: Codable { 


    /** The unique order reference used by the Channel. */
    public var channelOrderNo: String
    public var lines: [ChannelShipmentLineResponse]
    /** The date at which the shipment was created in ChannelEngine. */
    public var createdAt: Date?
    /** The date at which the shipment was last modified in ChannelEngine. */
    public var updatedAt: Date?
    /** The unique shipping reference used by the Shipping carrier (track&amp;trace number). */
    public var trackTraceNo: String?
    /** A link to a page of the carrier where the customer can track the shipping of her package. */
    public var trackTraceUrl: String?
    /** The unique return shipping reference that may be used by the Shipping carrier (track &amp; trace number) if the shipment is returned. */
    public var returnTrackTraceNo: String?
    /** Shipment method: the carrier used for shipping the package. E.g. DHL, postNL. */
    public var method: String?

    public init(channelOrderNo: String, lines: [ChannelShipmentLineResponse], createdAt: Date? = nil, updatedAt: Date? = nil, trackTraceNo: String? = nil, trackTraceUrl: String? = nil, returnTrackTraceNo: String? = nil, method: String? = nil) {
        self.channelOrderNo = channelOrderNo
        self.lines = lines
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.trackTraceNo = trackTraceNo
        self.trackTraceUrl = trackTraceUrl
        self.returnTrackTraceNo = returnTrackTraceNo
        self.method = method
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case channelOrderNo = "ChannelOrderNo"
        case lines = "Lines"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case trackTraceNo = "TrackTraceNo"
        case trackTraceUrl = "TrackTraceUrl"
        case returnTrackTraceNo = "ReturnTrackTraceNo"
        case method = "Method"
    }

}
