//
// ChannelOrderLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelOrderLineRequest: Codable, Hashable {

    /** The unique product reference used by the channel. */
    public var channelProductNo: String
    /** The unique product reference used by the merchant. */
    public var merchantProductNo: String?
    /** The number of items of the product. */
    public var quantity: Int
    /** The number of items for which cancellation was requested by the customer.  Some channels allow a customer to cancel an order until it has been shipped.  When an order has already been acknowledged in ChannelEngine, it can only be cancelled by creating a cancellation.  Use this field to check whether it is still possible to cancel the order. If this is the case, submit a cancellation to ChannelEngine. */
    public var cancellationRequestedQuantity: Int?
    /** The value of a single unit of the ordered product including VAT  (in the shop's base currency calculated using the exchange rate at the time of ordering). */
    public var unitPriceInclVat: Double
    /** A fixed fee that is charged by the Channel for this orderline.  This fee rate is based on the currency of the Channel  This field is optional, send 0 if not applicable. */
    public var feeFixed: Double?
    /** A percentage fee that is charged by the Channel for this orderline.  This field is optional, send 0 if not applicable. */
    public var feeRate: Double?
    public var condition: Condition?
    /** Expected delivery date from channels, empty if channels not support this value */
    public var expectedDeliveryDate: Date?

    public init(channelProductNo: String, merchantProductNo: String? = nil, quantity: Int, cancellationRequestedQuantity: Int? = nil, unitPriceInclVat: Double, feeFixed: Double? = nil, feeRate: Double? = nil, condition: Condition? = nil, expectedDeliveryDate: Date? = nil) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
        self.cancellationRequestedQuantity = cancellationRequestedQuantity
        self.unitPriceInclVat = unitPriceInclVat
        self.feeFixed = feeFixed
        self.feeRate = feeRate
        self.condition = condition
        self.expectedDeliveryDate = expectedDeliveryDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
        case cancellationRequestedQuantity = "CancellationRequestedQuantity"
        case unitPriceInclVat = "UnitPriceInclVat"
        case feeFixed = "FeeFixed"
        case feeRate = "FeeRate"
        case condition = "Condition"
        case expectedDeliveryDate = "ExpectedDeliveryDate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelProductNo, forKey: .channelProductNo)
        try container.encodeIfPresent(merchantProductNo, forKey: .merchantProductNo)
        try container.encode(quantity, forKey: .quantity)
        try container.encodeIfPresent(cancellationRequestedQuantity, forKey: .cancellationRequestedQuantity)
        try container.encode(unitPriceInclVat, forKey: .unitPriceInclVat)
        try container.encodeIfPresent(feeFixed, forKey: .feeFixed)
        try container.encodeIfPresent(feeRate, forKey: .feeRate)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(expectedDeliveryDate, forKey: .expectedDeliveryDate)
    }
}

