//
// ChannelReturnLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelReturnLineRequest: Codable, Hashable {

    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?
    /** The unique product reference used by the Merchant. */
    public var merchantProductNo: String?
    /** Number of items of the product in this return. */
    public var quantity: Int
    /** Extra data on the returnline. Each item must have an unqiue key */
    public var extraData: [String: String]?

    public init(channelProductNo: String? = nil, merchantProductNo: String? = nil, quantity: Int, extraData: [String: String]? = nil) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
        case extraData = "ExtraData"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channelProductNo, forKey: .channelProductNo)
        try container.encodeIfPresent(merchantProductNo, forKey: .merchantProductNo)
        try container.encode(quantity, forKey: .quantity)
        try container.encodeIfPresent(extraData, forKey: .extraData)
    }
}

