//
// ChannelProductReferencesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelProductReferencesRequest: Codable, Hashable {

    /** The unique ChannelEngine product ID. */
    public var id: Int?
    /** The unique product reference used by the Channel. */
    public var channelProductNo: String

    public init(id: Int? = nil, channelProductNo: String) {
        self.id = id
        self.channelProductNo = channelProductNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case channelProductNo = "ChannelProductNo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(channelProductNo, forKey: .channelProductNo)
    }
}

