//
// ChannelProductReferencesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelProductReferencesRequest: Codable { 


    /** The unique ChannelEngine product ID. */
    public var id: Int?
    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?

    public init(id: Int? = nil, channelProductNo: String? = nil) {
        self.id = id
        self.channelProductNo = channelProductNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id = "Id"
        case channelProductNo = "ChannelProductNo"
    }

}
