//
// ChannelReturnLineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ChannelReturnLineResponse: Codable { 


    /** The unique product reference used by the Channel. */
    public var channelProductNo: String
    /** The unique product reference used by the Merchant. */
    public var merchantProductNo: String?
    /** The number of accepted items of the product in this return (should normally be refunded). */
    public var acceptedQuantity: Int?
    /** The number of rejected items of the product in this return (should normally not be refunded). */
    public var rejectedQuantity: Int?
    /** Number of items of the product in this return. */
    public var quantity: Int

    public init(channelProductNo: String, merchantProductNo: String? = nil, acceptedQuantity: Int? = nil, rejectedQuantity: Int? = nil, quantity: Int) {
        self.channelProductNo = channelProductNo
        self.merchantProductNo = merchantProductNo
        self.acceptedQuantity = acceptedQuantity
        self.rejectedQuantity = rejectedQuantity
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case channelProductNo = "ChannelProductNo"
        case merchantProductNo = "MerchantProductNo"
        case acceptedQuantity = "AcceptedQuantity"
        case rejectedQuantity = "RejectedQuantity"
        case quantity = "Quantity"
    }

}
