//
// DataChangesProductType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum DataChangesProductType: String, Codable, CaseIterable {
    case single = "SINGLE"
    case parent = "PARENT"
    case child = "CHILD"
    case grandparent = "GRANDPARENT"
}
