//
// ProductType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ProductType: String, Codable, CaseIterable {
    case single = "SINGLE"
    case parent = "PARENT"
    case child = "CHILD"
    case grandparent = "GRANDPARENT"
    case bundle = "BUNDLE"
}
