//
// ShipmentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum ShipmentStatus: String, Codable, CaseIterable {
    case pending = "PENDING"
    case closed = "CLOSED"
}
