//
// CancellationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CancellationAPI {
    /**
     Get Cancellations
     
     - parameter createdSince: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func cancellationIndex(createdSince: Date? = nil, completion: @escaping ((_ data: CollectionOfChannelCancellationResponse?,_ error: Error?) -> Void)) {
        cancellationIndexWithRequestBuilder(createdSince: createdSince).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Cancellations
     - GET /v2/cancellations
     - Gets all cancellations created since the supplied date.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "TotalCount" : 1,
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "Content" : [ {
    "ChannelOrderNo" : "ChannelOrderNo",
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "ReasonCode" : "NOT_IN_STOCK",
    "Reason" : "Reason",
    "Lines" : [ {
      "Quantity" : 0,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Quantity" : 0,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  }, {
    "ChannelOrderNo" : "ChannelOrderNo",
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "ReasonCode" : "NOT_IN_STOCK",
    "Reason" : "Reason",
    "Lines" : [ {
      "Quantity" : 0,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Quantity" : 0,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  } ],
  "ItemsPerPage" : 5,
  "Count" : 6,
  "StatusCode" : 5,
  "LogId" : 2,
  "Success" : true
}}]
     
     - parameter createdSince: (query)  (optional)

     - returns: RequestBuilder<CollectionOfChannelCancellationResponse> 
     */
    open class func cancellationIndexWithRequestBuilder(createdSince: Date? = nil) -> RequestBuilder<CollectionOfChannelCancellationResponse> {
        let path = "/v2/cancellations"
        let URLString = ChannelEngineChannelApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "createdSince": createdSince?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<CollectionOfChannelCancellationResponse>.Type = ChannelEngineChannelApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
